version: "3.1"

services:
  frontend:
    container_name: frontend
    depends_on:
      - server-a
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        VITE_API_URL: "http://tie-webarc-1.it.tuni.fi:3000"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - front
  server-a:
    container_name: server-a
    depends_on:
      - rabbitmq
      - mongodb
      - server-b
    build:
      dockerfile: Dockerfile
      context: ./backend/server-a
    restart: always
    ports:
      - "3000:3000"
    environment:
      EXPRESS_PORT: 3000
      MONGO_URL: "mongodb://username:password@mongodb:27017/sandapp?authSource=sandapp" # example value, change it.
      JWT_SECRET: "AizJPFHsMkQ8WYqF1Q6YmWiD" # example value, change it.
      RABBITMQ_URL: "amqp://username:password@rabbitmq:5672" # example value, change it.
    networks:
      - front
      - rabbitmq
      - mongodb
  server-b:
    container_name: server-b
    depends_on:
      - rabbitmq
    build:
      dockerfile: Dockerfile
      context: ./backend/server-b
    restart: always
    environment:
      RABBITMQ_URL: "amqp://username:password@rabbitmq:5672"
    networks:
      - rabbitmq

  mongodb:
    container_name: mongodb
    # The registry is precised because the VM config previledges the RedHat registries before
    image: "docker.io/bitnami/mongodb:4.4"
    environment:
      MONGODB_ROOT_PASSWORD: "root" # example value, change it.
      MONGODB_USERNAME: "username" # example value, change it.
      MONGODB_PASSWORD: "password" # example value, change it.
      MONGODB_DATABASE: "sandapp"
    volumes:
      - "mongodb_data:/bitnami/mongodb"
    networks:
      - mongodb

  rabbitmq:
    container_name: rabbitmq
    image: "docker.io/bitnami/rabbitmq:latest"
    environment:
      - RABBITMQ_USERNAME=username # example value, change it.
      - RABBITMQ_PASSWORD=password # example value, change it.
    networks:
      - rabbitmq
    volumes:
      - rabbitmq_data:/bitnami

networks:
  front:
    driver: bridge
  mongodb:
    internal: true
    driver: bridge
  rabbitmq:
    internal: true
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
